name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Google Cloud authentication
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Build the Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/summarizer .

      - name: Push Docker image to Artifact Registry
        run: |
          # Log in to Google Cloud Artifact Registry
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
          
          # Tag the Docker image for Artifact Registry (use a version tag, e.g., v1)
          docker tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/summarizer us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/summarizer-repo/summarizer:v1

          # Push the image to Artifact Registry
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/summarizer-repo/summarizer:v1

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy summarizer \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/summarizer-repo/summarizer:v1 \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
